### PR TITLE
Issue 82 fix

### PR DESCRIPTION
**Pull request by mindblender**
Multiple fixes for #82 Can't Reset Password

### CODE REVIEW

**Comment by mindblender** [comment]
@nhoknakroz could you take a look and see if these changes fix the issue you found?  Thanks!

**Comment by nhoknakroz** [comment]
@mindblender I saw that in file `general/resetpassword.php` you have modified line 11 to:
```php
$token = $request->query->get("token") || $request->request->get("token");
```
then `$token` became a boolean variable will be invalid in line 108.
In my opinion you should change line 11 to:
```php
$token = $request->query->get("token") ?? $request->request->get("token");
```

**Comment by nhoknakroz** [comment]
@mindblender In file `classes/Members/ResetPassword` at line 173-175:
```php
if ($this->isTimestampExpired($this->timestamp)) {
                    $this->resetPassword($this->userDetails["id"], $request->request->get("password"));
}
```
I think you should change to:
```php
if (!$this->isTimestampExpired($this->timestamp)) {
                    $this->resetPassword($this->userDetails["id"], $request->request->get("password"));
}
```

**Comment by mindblender** [comment]
Thanks @nhoknakroz for the feedback and suggestions!

**Pull request merged**
